# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: nvm install node && nvm use 16 && yarn install # runs during prebuild
    command: git config --global user.email $GIT_COMMITTER_EMAIL && git config --global user.name $GIT_AUTHOR_NAME # runs on startup

