module.exports = {
  apps: [
    {
      name: "fire",
      script: "dist/src/index.js",
      exec_mode: "fork",
      instances: 4,
      instance_var: "INSTANCE_ID",
      wait_ready: true,
      listen_timeout: 30000,
      kill_timeout: 3000,
      post_update: ["pnpm compile"],
      automation: false,
      env: {
        NODE_ENV: "production",
      },
      max_restarts: 5,
      max_memory_restart: "1G",
      exp_backoff_restart_delay: 2500,
      node_args: "--enable-source-maps",
    },
    {
      name: "fire-dev",
      script: "dist/src/index.js",
      automation: false,
      kill_timeout: 3000,
      post_update: ["pnpm compile"],
      env: {
        NODE_ENV: "development",
      },
      max_restarts: 5,
      max_memory_restart: "1G",
      exp_backoff_restart_delay: 2500,
      node_args: "--enable-source-maps",
    },
    {
      name: "fire-beta",
      script: "dist/src/index.js",
      exec_mode: "fork",
      instances: 1,
      instance_var: "INSTANCE_ID",
      wait_ready: true,
      listen_timeout: 30000,
      kill_timeout: 3000,
      post_update: ["pnpm compile"],
      automation: false,
      env: {
        NODE_ENV: "staging",
      },
      max_restarts: 5,
      max_memory_restart: "1G",
      exp_backoff_restart_delay: 2500,
      node_args: "--enable-source-maps",
    },
  ],
};
